<?php

namespace App\Http\Controllers;

use App\Models\VibeSession;
use App\Services\SpotifyService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;

class VibeController extends Controller
{
    public function __construct(private SpotifyService $spotify)
    {
    }

    /**
     * Show the dashboard / upload page.
     */
    public function dashboard()
    {
        $sessions = Auth::user()->vibeSessions()->latest()->take(5)->get();
        return view('dashboard', compact('sessions'));
    }

    /**
     * Handle image upload, call AI service, store vibe session.
     */
    public function analyze(Request $request)
    {
        $request->validate([
            'image' => 'required|image|max:10240',
        ]);

        $user = Auth::user();
        $image = $request->file('image');

        // Store the uploaded image
        $path = $image->store('vibes', 'public');

        // Call the Python AI microservice
        $aiServiceUrl = env('AI_SERVICE_URL', 'http://localhost:8001');

        try {
            $response = Http::timeout(60)
                ->attach('image', file_get_contents($image->getRealPath()), $image->getClientOriginalName())
                ->post("{$aiServiceUrl}/analyze-image");

            if (!$response->successful()) {
                return back()->withErrors(['image' => 'AI service failed to analyze the image. Please try again.']);
            }

            $vibe = $response->json();

        } catch (\Exception $e) {
            return back()->withErrors(['image' => 'Could not connect to AI service: ' . $e->getMessage()]);
        }

        // Save vibe session
        $session = VibeSession::create([
            'user_id' => $user->id,
            'image_path' => $path,
            'caption' => $vibe['caption'] ?? null,
            'keywords' => $vibe['keywords'] ?? [],
            'energy' => $vibe['energy'] ?? 0.5,
            'valence' => $vibe['valence'] ?? 0.5,
            'tempo' => $vibe['tempo'] ?? 120,
            'acousticness' => $vibe['acousticness'] ?? 0.5,
        ]);

        return redirect()->route('vibe.result', $session->id);
    }

    /**
     * Show vibe analysis result and allow playlist creation.
     */
    public function result(VibeSession $session)
    {
        $this->authorize('view', $session);

        // Get track recommendations preview from Spotify
        $user = Auth::user();
        $token = $this->getFreshToken($user);
        $tracks = [];

        if ($token) {
            $tracks = $this->spotify->getRecommendations(
                $token,
                $session->energy,
                $session->valence,
                $session->tempo,
                $session->acousticness ?? 0.5
            );
        }

        return view('vibe.result', compact('session', 'tracks'));
    }

    /**
     * Create a Spotify playlist from the vibe session.
     */
    public function createPlaylist(Request $request, VibeSession $session)
    {
        $this->authorize('update', $session);

        $user = Auth::user();
        $token = $this->getFreshToken($user);

        if (!$token) {
            return back()->withErrors(['spotify' => 'Spotify authentication failed. Please login again.']);
        }

        // Get recommendations
        $tracks = $this->spotify->getRecommendations(
            $token,
            $session->energy,
            $session->valence,
            $session->tempo,
            $session->acousticness ?? 0.5
        );

        if (empty($tracks)) {
            return back()->withErrors(['spotify' => 'No tracks found for this vibe. Try a different image.']);
        }

        // Generate playlist name
        $keywords = $session->keywords ?? [];
        $topKeywords = implode(', ', array_slice($keywords, 0, 3));
        $playlistName = "Vibe: " . ($topKeywords ?: 'My Playlist') . " 🎵";
        $description = "Generated by Vibe Playlist Generator from image analysis. " .
            "Energy: {$session->energy}, Valence: {$session->valence}";

        // Create playlist on Spotify
        $playlist = $this->spotify->createPlaylist(
            $token,
            $user->spotify_id,
            $playlistName,
            $description
        );

        if (!$playlist) {
            return back()->withErrors(['spotify' => 'Failed to create Spotify playlist.']);
        }

        // Add tracks
        $trackUris = array_column($tracks, 'uri');
        $this->spotify->addTracksToPlaylist($token, $playlist['id'], $trackUris);

        // Update session
        $session->update([
            'playlist_id' => $playlist['id'],
            'playlist_url' => $playlist['external_urls']['spotify'] ?? null,
            'playlist_name' => $playlistName,
        ]);

        return redirect()->route('vibe.result', $session->id)
            ->with('success', 'Playlist created successfully! 🎶');
    }

    /**
     * Show vibe session history.
     */
    public function history()
    {
        $sessions = Auth::user()->vibeSessions()->latest()->paginate(12);
        return view('vibe.history', compact('sessions'));
    }

    /**
     * Get a fresh access token, refreshing if needed.
     */
    private function getFreshToken($user): ?string
    {
        // Check if token needs refresh (simple approach)
        if ($user->spotify_refresh_token) {
            $refreshed = $this->spotify->refreshAccessToken($user->spotify_refresh_token);
            if ($refreshed && isset($refreshed['access_token'])) {
                $user->update(['spotify_token' => $refreshed['access_token']]);
                return $refreshed['access_token'];
            }
        }

        return $user->spotify_token;
    }
}
